
/**************************************************************
 *	
 *	bgMusic, 8 bit, 11025Hz,
 *	1 channel, 1542528 bytes/channel
 *	Total Size: 1 * 1542528 + 4 (header) = 1542572 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	\\prism.nas.gatech.edu\rcobelli3\Desktop\bgMusic.wav
 *	Time-stamp: Sat Nov 23 17:40:33 2019
 *	
 **************************************************************/

#ifndef __BGMUSICH__
#define __BGMUSICH__

#define BGMUSICFREQ 11025
#define BGMUSICLEN 1542528

extern const unsigned char bgMusic[1542528];

#endif /* __BGMUSICH__ */
