
/**************************************************************
 *	
 *	error, 8 bit, 11025Hz,
 *	1 channel, 13253 bytes/channel
 *	Total Size: 1 * 13253 + 4 (header) = 13297 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	\\prism.nas.gatech.edu\rcobelli3\Desktop\error.wav
 *	Time-stamp: Sat Nov 23 17:39:34 2019
 *	
 **************************************************************/

#ifndef __ERRORH__
#define __ERRORH__

#define ERRORFREQ 11025
#define ERRORLEN 13253

extern const unsigned char error[13253];

#endif /* __ERRORH__ */
